version: "3.9"

services:
  haproxy:
    image: envoyproxy/envoy-dev:latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "5001:9901"
      - "5000:10000"
    depends_on:
      - api
    networks:
      - my_network

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:80
    ports:
      - "80"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
