version: "3.9"

services:
  nginx:
    image: nginx:alpine
    hostname: "nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - "5000:80"
    depends_on:
      - api1
      - api2
      - api3
      - api4
      - api5
    networks:
      - my_network
    restart: always

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:80
    ports:
      - "80"
    networks:
      - my_network
    restart: always

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:80
    ports:
      - "80"
    networks:
      - my_network
    restart: always

  api3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:80
    ports:
      - "80"
    networks:
      - my_network
    restart: always

  api4:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:80
    ports:
      - "80"
    networks:
      - my_network
    restart: always

  api5:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:80
    ports:
      - "80"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
