version: "3.9"

services:
  haproxy:
    image: haproxy:alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "5000:80"
    depends_on:
      - api
    networks:
      - my_network

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:80
    ports:
      - "80"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
