version: "3.9"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/:/var/log/nginx/
    ports:
      - "5000:80"
    depends_on:
      - api
    networks:
      - my_network
    restart: always

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:80
    ports:
      - "80"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
