version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    image: levdeo/demoapi
    environment:
      ASPNETCORE_URLS: http://+:5000
    ports:
      - "80:5000"
    restart: always
