version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    image: levdeo/demoapi
    environment:
      ASPNETCORE_URLS: http://+:80
    ports:
      - "5000:80"
    restart: always
